image:
        name: cameronnemo/gitlab-ci-brillo
        entrypoint: [""]

stages:
        - lint
        - build

before_script:
        - xbps-install -Syu

cppcheck:
        stage: lint
        script: cppcheck --inline-suppr --error-exitcode=3 .

make:
        stage: build
        script: make
